import Ibm from "./ibm.jpg";
import Airbnb from "./airbnb.jpg";
import Fb from "./fb.png";
import Google from "./google.png";
import Mongo from "./mongo.jpg";
import React_logo from "./react-logo-825x510.jpg";
import First from "./23andme.svg";
import Second from "./activision.svg";
import Third from "./airbnb.svg";
import Fourth from "./airbnb-logo.svg";
import Fifth from "./akamaitechnologies.svg";
import Sixth from "./atlassian.svg";
import Seventh from "./blend.svg";
import Eighth from "./cloudera.svg";
import Ninth from "./doordash.svg";
import Ten from "./honey.svg";
import Eleven from "./jpmorgan.svg";
import Twelve from "./lime.svg";
import Thirteen from "./lyft.svg";
import Fourteen from "./mongodb.svg";
import Fifteen from "./nerdwallet.svg";
import Sixteen from "./pinterest.svg";
import Seventeen from "./plaid.svg";
import Eighteen from "./samsara.svg";
import Nineteen from "./stripe.svg";
import Twenty from "./toast.svg";
import Twentyone from "./twitch.svg";
export const ibm = Ibm;
export const airbnb = Airbnb;
export const fb = Fb;
export const google = Google;
export const mongo = Mongo;
export const react = React_logo;
export const first = First;
export const second = Second;
export const third = Third;
export const fourth = Fourth;
export const fifth = Fifth;
export const sixth = Sixth;
export const seventh = Seventh;
export const eighth = Eighth;
export const ninth = Ninth;
export const tenth = Ten;
export const eleven = Eleven;
export const twelve = Twelve;
export const thirteen = Thirteen;
export const fourteen = Fourteen;
export const fifteen = Fifteen;
export const sixteen = Sixteen;
export const seventeen = Seventeen;
export const eighteen = Eighteen;
export const nineteen = Nineteen;
export const twenty = Twenty;
export const twentyone = Twentyone;
